import React from "react";
import { Inter } from "next/font/google";
import StyledComponentsRegistry from "../lib/AntdRegistry";
import AppLayout from "@/components/Layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="ko">
    <body className={inter.className} style={{ margin: 0 }}>
      <StyledComponentsRegistry>
        <AppLayout>{children}</AppLayout>
      </StyledComponentsRegistry>
    </body>
  </html>
);

export default RootLayout;
