import React from "react";
import { Inter } from "next/font/google";
import StyledComponentsRegistry from "../lib/AntdRegistry";
import AppLayout from "@/components/Layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <body className={inter.className}>
    <StyledComponentsRegistry>
      <AppLayout>{children}</AppLayout>
    </StyledComponentsRegistry>
  </body>
);

export default RootLayout;
